pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: Test
    displayName: "test"
    jobs:
      - job: baseline
        displayName: Compute Packages to test
        steps:
          - bash: |
              PACKAGES_TO_TEST="{ '@daffodil/daffio': { 'name': '@daffodil/daffio', 'version': '0.0.0-PLACEHOLDER', 'private': true, 'location': '/home/damien/graycore/daffodil/apps/daffio' } }"
              echo "##vso[task.setvariable variable=packagesToTest;isOutput=true;]$PACKAGES_TO_TEST"
            name: packages
      - job: test
        displayName: "Test"
        strategy:
          matrix: $[ dependencies.baseline.outputs['packages.packagesToTest'] ]
        dependsOn: 
          - baseline
        steps: 
        - script: echo $(name)
          displayName: Echo Package Name

