pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: Test
    displayName: "test"
    jobs:
      - job: baseline
        displayName: Compute Packages to test
        steps:
          - bash: |
              PACKAGES_TO_TEST=$(jq -c . < example.json)
              echo "##vso[task.setvariable variable=packagesToTest;isOutput=true;]$PACKAGES_TO_TEST"
            name: Compute Packages
      - job: test
        displayName: "Test"
        strategy:
          matrix: $[ dependencies.baseline.outputs['packages.packagesToTest'] ]
        dependsOn: 
          - baseline
        steps: 
        - script: echo $(name)
          displayName: Echo Package Name

