pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: Test
    displayName: "test"
    jobs:
      - job: baseline
        displayName:
        steps:
          - bash: |
              PACKAGES_TO_TEST="[{ 'name': '@daffodil/daffio', 'version': '0.0.0-PLACEHOLDER', 'private': true, 'location': '/home/damien/graycore/daffodil/apps/daffio' }]"
              echo "##vso[task.setvariable variable=packagesToTest;isOutput=true;]$PACKAGES_TO_TEST"
      - template: .azure/templates/echo-job.yaml
        parameters:
          dependsOn: 
            - baseline
          packages:
            names: $[ dependencies.baseline.outputs['packagesToTest'] ]

