pool:
  vmImage: 'ubuntu-latest'

stage:
  - stage: Test
    displayName: "test"
    jobs:
      - job: baseline
        displayName:
        steps:
          - task: NodeTool@0 
            inputs:
              versionSpec: 12.x
      - template: .azure/templates/echo-job.yml
        parameters:
          packages: 
            names: ["@daffodil/cart"]
