# job.yml
parameters:
- name: 'packages'
  type: object
  default: 
    names: []
- name: 'dependsOn'
  type: object
  default: []

jobs:
  - ${{ each package in parameters.packages.names }}: # Then do each job
    - job: test_${{ replace(replace(package,'@',''),'/','_') }}
      displayName: "Test ${{ package }}"
      ${{ if job.dependsOn }}:
      dependsOn: ${{ job.dependsOn }}
      steps: 
        - script: echo ${{ package }}