# job.yml
parameters:
- name: 'packages'
  type: object
  default: 
    names: []
- name: 'dependsOn'
  type: object
  default: []
- name: 'variables'
  type: object
  default: {}
- name: 'steps'
  type: stepList
  default: []

jobs:

