# job.yml
parameters:
- name: 'packages'
  type: object
  default: 
    names: []
- name: 'dependsOn'
  type: object
  default: []
- name: 'variables'
  type: object
  default: {}
- name: 'steps'
  type: stepList
  default: []

jobs:
  - ${{ each package in parameters.packages.names }}: # Then do each job
    - job: test_${{ replace(replace(package,'@',''),'/','_') }}
      displayName: "Test ${{ package }}"
      ${{ if parameters.variables }}:
        variables: ${{ parameters.variables }}
      ${{ if parameters.dependsOn }}:
        dependsOn: ${{ parameters.dependsOn }}
      steps: 
        - script: echo ${{ package }}
        - ${{ parameters.steps }}
