# job.yml
parameters:
- name: 'packages'
  type: object
  default: 
    names: []

jobs:
  - ${{ each package in parameters.packages.names }}: # Then do each job
    name: "Test ${{ package }}"
    steps: 
      script: echo ${{ package }}