# job.yml
parameters:
- name: 'packages'
  type: object
  default: 
    names: []

jobs:
  - ${{ each package in parameters.packages.names }}: # Then do each job
    - job: test_${{ replace(package,'@','_') }}
      displayName: "Test ${{ package }}"
      steps: 
        - script: echo ${{ package }}